spring.application.name=MedicineSystemAPI

spring.datasource.url=jdbc:postgresql://localhost:5432/MedicineDB_MedSystem
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.error.whitelabel.enabled=false
server.error.include-message=always
server.error.path=/error
server.error.page404=/error/404

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

springdoc.swagger-ui.path=/api/docs
